Digard Network Test - DIGA
ava-labs/avalanche-faucet pull request #25
Opened 2022-06-16 21:37 UTC by kemal-arbeiter

2022-06-30 18:23 UTC, rajranjan0608 commented
Hi @kemal-arbeiter. Can you also put a link to the indexed explorer in the config file?

2022-07-01 13:46 UTC, kemal-arbeiter commented
done, please check

2022-07-04 10:40 UTC, rajranjan0608 commented
Thank you very much. This LGTM.

2022-07-04 10:43 UTC, rajranjan0608 requested changes
Added a few nits. Thanks

2022-07-04 10:43 UTC, rajranjan0608 commented on config.json
> +            "EXPLORER": "https://testnet.avascan.info/blockchain/digard/home",
Can you remove `home` from the explorer URL? Avascan now supports redirection from the base endpoint.

2022-07-04 10:43 UTC, rajranjan0608 commented on config.json
> +            "IMAGE": "https://cdn.digard.io/digard.jpg",
Would you like to use a PNG or image with a transparent background here? I am ok with both...

2022-07-06 16:24 UTC, kemal-arbeiter commented on config.json
> +            "EXPLORER": "https://testnet.avascan.info/blockchain/digard/home",
fixed

2022-07-06 16:24 UTC, kemal-arbeiter commented on config.json
> +            "IMAGE": "https://cdn.digard.io/digard.jpg",
fixed

2022-07-06 16:37 UTC, rajranjan0608 commented
Awesome 🤝

2022-07-06 16:37 UTC, rajranjan0608 approved these changes

2022-07-06 16:37 UTC, merged

2022-07-06 16:41 UTC, rajranjan0608 commented
@kemal-arbeiter Make sure to send funds to one and only faucet address -  0x2352D20fC81225c8ECD8f6FaA1B37F24FEd450c9